version: 2.1

orbs:
  reporting: ministryofjustice/hmpps-reporting@1.0.53
  slack: circleci/slack@4.12.5

parameters:
  workingdir:
    type: string
    default: '.'

jobs:
  validate:
    executor:
      name: hmpps/java
      tag: "21.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: << pipeline.parameters.workingdir >>
          paths:
            - .

workflows:
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/

  checkout-build-publish:
    jobs:
      - reporting/gradle_owasp_check:
          notify_slack: false
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          cache_key: "dpr-lambdas-build-cache-v2"
      - reporting/gradle_build_publish:
          tag: "11.0"
          app: digital-prison-reporting-lambdas
          app_artifacts_directory: build/libs/
          bucket_prefix: dpr-artifact-store
          sync_args: "--exclude '*' --include '*-all*jar'"
          deploy_to_test: true # Deploy to Test Environment
          refresh_lambda: true
          refresh_function: dpr-pipeline-notification-function
          notify_jira: true
          notify_slack: true
          channel: dpr_cicd_alerts
          command: jar shadowJar # Skip tests when building jar, they've already run
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
          ref: << pipeline.git.branch >><< pipeline.git.tag >>
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          cache_key: "dpr-lambdas-build-cache-v2"

  owasp-security:
    triggers:
      - schedule:
          cron: "30 6 * * *" ## Runs everyday at 7.30 AM UK TIME
          filters:
            branches:
              only:
                - main
    jobs:
      - reporting/gradle_owasp_check:
          notify_slack: true
          channel: dpr_cicd_alerts
          context:
            - hmpps-reporting-common
            - hmpps-reporting-orb
          cache_key: "dpr-lambdas-owasp-build-cache-v1"
